"""add status column to followers

Revision ID: e9de68ccdbd9
Revises: 
Create Date: 2026-09-12 22:52:15.878379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9de68ccdbd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'REJECTED', name='followrequest'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followers', 'status')
    # ### end Alembic commands ###
